# Generated by Django 3.0.2 on 2020-01-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0002_auto_20200123_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
