# Generated by Django 3.0.2 on 2020-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0003_auto_20200125_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='describe_text',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
