# Generated by Django 3.0.2 on 2020-01-25 21:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0004_post_describe_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='describe_text',
            field=models.TextField(blank=True, help_text='Описание которое выведиться на главной странице', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='Название', max_length=150),
        ),
    ]
